Create how_to_fix_python_3.6_socket_TypeError:_a_bytes-like_object_is_required,_not_str
 while True:
          cmd = input('data sent to server: ').strip()
          if cmd == '': continue
          conn.send(cmd)
TypeError: a bytes-like object is required, not 'str'
3) fix:   socket.send(data.encode()), socket.recv(1024).decode()