Create AttributeError:_module_object_has_no_attribute__string_to_bool_in_mplot3d
ax = fig.add_subplot(111, projection='3d')
AttributeError: 'module' object has no attribute '_string_to_bool' in mplot3d
    "in older release the toolkits were stored in a seperate folder mpl_toolkits 
    which have since been moved into the matplotlib folder. 
    Thus this version is not overwritten when installing a new version of matplotlib 
    and wrongly picked up when importing the toolkits."
        /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/mpl_toolkits/mplot3d-old
        pip install --upgrade matplotlib[mplot3d]