Create how_fo_fix_cherry-pick_conflict_could_not_apply_commit_in_git
error: could not apply 5a8b7fd... 
Root Cause:
	conflict in the changed file in this commit.
Fix:
	resolve the conflict in merge tool ex. BCompare.
	continue with commit.