Create how_to_debug_java.lang.OutOfMemoryError
Phenomenon:
[DEBUG] Cannot find ArtifactResolver with hint: project-cache-aware
org.codehaus.plexus.component.repository.exception.ComponentLookupException: java.util.NoSuchElementException
      role: org.apache.maven.artifact.resolver.ArtifactResolver
  roleHint: project-cache-aware
...
at org.codehaus.plexus.util.DirectoryScanner.scandir(DirectoryScanner.java:521)

debug steps:
1) reset JVM heap size: local maven build NOT ok.
	#NOT ok export MAVEN_OPTS='-Xms512m -Xmx1024m -XX:MaxMetaspaceSize=512m'
Root cause:
	directory in ***/src/assembly/main.xml was set wrong: was set to / root directory on linux.